name: DDNS Updater
version: "2.9.0-ha1.0.5"
slug: ddns_updater
description: Universal DNS updater with support for multiple DNS providers utilizing ddns-updater.
arch:
  - aarch64
  - amd64
url: "https://github.com/ha-ddns-updater/ha-ddns-updater"
# startup: application
webui: "http://[HOST]:[PORT:8000]/"
# boot: auto
ports:
  "8000/tcp": 8000
ports_description:
  "8000/tcp": "Web UI for monitoring and management"
map:
  - type: data
    path: "/updater/data"
environment:
  HA_OPTIONS_FILEPATH: "/updater/data/options.json"
legacy: true # TODO: necessary? false needs some image labels
options:
  environments:
    PERIOD: "5m"
    SERVER_ENABLED: "yes"
    LOG_LEVEL: "info"
  settings:
    - provider: "duckdns"
      domain: "example.duckdns.org"
      token: "00000000-0000-0000-0000-000000000000"
    - provider: "cloudflare"
      domain: "example.com"
      owner: "subdomain"
      email: "user@example.com"
      key: "your-api-key"
# schema: false # disabled because the linter doesn't like it
image: "docker.io/haddnsupdater/ha-ddns-updater"
# ingress: # TODO: might be useful for webui
init: false
#watchdog: # TODO
